### ISSUE TITLE
Not able to install it properly

### ISSUE THREAD

**Issue by Shekharrajak** [ntasfi/PyGame-Learning-Environment#63]
```
(py36)  ➜  PyGame-Learning-Environment git:(master) sudo pip install -e .

The directory '/home/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/PyGame-Learning-Environment
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages (from ple==0.0.1)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from ple==0.0.1)
Installing collected packages: ple
  Found existing installation: ple 0.0.1
    Can't uninstall 'ple'. No files were found to uninstall.
  Running setup.py develop for ple
Successfully installed ple
(py36)   PyGame-Learning-Environment git:(master) pip install gym_ple
Collecting gym_ple
  Using cached https://files.pythonhosted.org/packages/0d/d6/41e3510bf943a6383b89d1b3db785efbd2c63c55ac2947a4ba31bf9c9009/gym_ple-0.3.tar.gz
Building wheels for collected packages: gym-ple
  Running setup.py bdist_wheel for gym-ple ... done
  Stored in directory: /home/.cache/pip/wheels/48/a7/28/fd4f7105b5960ce04ddeb161679e2343a02e037ec34e992a54
Successfully built gym-ple
Installing collected packages: gym-ple
Successfully installed gym-ple-0.3
(py36)   PyGame-Learning-Environment git:(master) python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ple
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/PyGame-Learning-Environment/ple/__init__.py", line 1, in <module>
    from .ple import PLE
  File "/home/shekharrajak/Documents/githubRepos/personal/rl_games/tools/PyGame-Learning-Environment/ple/ple.py", line 5, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
>>> exit()
(py36) PyGame-Learning-Environment git:(master) pip install pygame
Collecting pygame
  Downloading https://files.pythonhosted.org/packages/8e/24/ede6428359f913ed9cd1643dd5533aefeb5a2699cc95bea089de50ead586/pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl (11.4MB)
    100% |████████████████████████████████| 11.4MB 2.5MB/s 
Installing collected packages: pygame
Successfully installed pygame-1.9.6
(py36) PyGame-Learning-Environment git:(master) python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ple
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
couldn't import doomish
Couldn't import doom
>>> 

```

Let me know if I did something wrong.

**Comment by wiederma** [comment]
Hi there,
I am trying to get some other pygame application running and found this instructions.
I got it (semi) working: having docker installed I followed the instructions provided: "docker build -t ple ."

I had to edit the Dockerfile: libav-tools seems deprecated and not available anymore ... replaced it with ffmpeg

Another issue is the "\" in the docker run command, just remove it and "docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY ple /bin/bash" drops you to a /bin/bash as root in your docker container.
